import Foundation

/// FlashFloppy **indexed** mode: `indexed-prefix` + 4-digit slot + wildcard. With **empty** prefix (FF 3.44 VFX rack),
/// files are `0000_*.*`, `0001_*.*`, … — the full name (including friendly text after `_`) scrolls on the OLED.
/// Optional non-empty prefix (e.g. `DSKA`) yields `DSKA0000_*.*` per wiki.
enum GotekIndexedDisplayNaming {
    /// FAT-safe suffix: whitespace → `_`, collapse runs of `_`, trim edges (matches `tools/apply_vfx_rack_friendly_indexed_names.py` spirit).
    static func sanitizeFilenameSuffix(_ raw: String) -> String {
        var s = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        let bad = CharacterSet(charactersIn: "\\/:*?\"<>|")
        s = s.components(separatedBy: bad).joined(separator: "_")
        s = s.replacingOccurrences(of: "\\s+", with: "_", options: .regularExpression)
        while s.contains("__") {
            s = s.replacingOccurrences(of: "__", with: "_")
        }
        s = s.trimmingCharacters(in: CharacterSet(charactersIn: "_."))
        if s.count > 180 {
            s = String(s.prefix(180)).trimmingCharacters(in: CharacterSet(charactersIn: "_."))
        }
        return s.isEmpty ? "disk" : s
    }

    /// Minimal indexed name: `0000.hfe` with empty prefix, or `DSKA0000.hfe` with prefix `DSKA`.
    static func plainIndexedFileName(slot: Int, prefix: String, fileExtension: String) -> String {
        let p = ExportNaming.normalizedIndexedPrefix(prefix)
        let idx = max(0, min(slot, 9999))
        let ext = normalizedExtension(fileExtension)
        return "\(p)\(String(format: "%04d", idx))\(ext)"
    }

    /// OLED-friendly: `0000_Descriptive_Name.ext` (empty prefix) or `DSKA0000_Descriptive_Name.ext`.
    static func indexedFileName(slot: Int, prefix: String, friendlyLabel: String, fileExtension: String) -> String {
        let p = ExportNaming.normalizedIndexedPrefix(prefix)
        let idx = max(0, min(slot, 9999))
        let ext = normalizedExtension(fileExtension)
        let suffix = sanitizeFilenameSuffix(friendlyLabel)
        return "\(p)\(String(format: "%04d", idx))_\(suffix)\(ext)"
    }

    private static func normalizedExtension(_ fileExtension: String) -> String {
        var e = fileExtension.trimmingCharacters(in: .whitespaces)
        if !e.hasPrefix(".") { e = "." + e }
        return e.lowercased()
    }
}

// MARK: - VFX rack catalog → bash rename helper

struct VFXRackCatalogSlot: Decodable {
    let slot: Int
    let indexed_filename: String?
    let friendly_label: String
}

struct VFXRackCatalogFile: Decodable {
    let slots: [VFXRackCatalogSlot]
}

enum VFXRackFriendlyIndexedRenameScript {
    /// If plain `####.ext` (empty prefix) or `PREFIX####.ext` exists, rename to catalog `indexed_filename`.
    static func bashScript(catalog: VFXRackCatalogFile, indexedPrefix: String = "") -> String {
        let p = ExportNaming.normalizedIndexedPrefix(indexedPrefix)
        var lines: [String] = [
            "#!/bin/bash",
            "# Generated by VFX-CTRL — apply friendly indexed names from VFX_RACK_CATALOG.json.",
            "# Run from the USB stick root.",
            "set -euo pipefail",
            "",
        ]
        for s in catalog.slots.sorted(by: { $0.slot < $1.slot }) {
            guard let target = s.indexed_filename, let dot = target.lastIndex(of: ".") else { continue }
            let extWithDot = String(target[dot...])
            let extLower = extWithDot.lowercased()
            let plain = p.isEmpty
                ? String(format: "%04d%@", s.slot, extLower)
                : String(format: "%@%04d%@", p, s.slot, extLower)
            guard plain.caseInsensitiveCompare(target) != .orderedSame else { continue }
            lines.append(
                "if [ -f \"\(plain)\" ] && [ ! -e \"\(target)\" ]; then mv -f \"\(plain)\" \"\(target)\"; fi"
            )
        }
        return lines.joined(separator: "\n") + "\n"
    }
}
